// everyday-market/everyday-market-react/src/components/market/ProductsPage/ProductsPage.js
import React from 'react';
import MarketService from '../../../services/marketService';
import {CategoryMenu, ProductList} from '../';

class ProductsPage extends React.Component {
  state = {
    categories: [],
    products: [],
  };

  componentDidMount() {
    MarketService.loadCategories()
      .then(o => this.setState({categories: o}));
  }

  onCategoryChanged = (category) => {
    MarketService.loadProducts(category.name)
      .then(o => this.setState({products: o}));
  }

  render() {
    return (
      <div>
        <CategoryMenu
          categories={this.state.categories}
          onCategoryChanged={this.onCategoryChanged}
        />
        <ProductList products={this.state.products} />
      </div>
    );
  }
}

export default ProductsPage;

// everyday-market/everyday-market-vue/src/components/market/ProductsPage.vue
<template>
  <div>
    <CategoryMenu
      :categories="categories"
      @category-changed="onCategoryChanged"
    />
    <ProductList :products="products" />
  </div>
</template>

<script>
import MarketService from '../../services/marketService';
import CategoryMenu from './CategoryMenu.vue';
import ProductList from './ProductList.vue';

export default {
  name: 'ProductsPage',
  components: {
    CategoryMenu,
    ProductList,
  },
  data: () => ({
    categories: [],
    products: [],
  }),
  mounted() {
    MarketService.loadCategories()
      .then(o => this.categories = o);
  },
  methods: {
    onCategoryChanged: function(category) {
      MarketService.loadProducts(category.name)
        .then(o => this.products = o);
    },
  },
}
</script>
